### ISSUE TITLE
can't be used on web: `Uint64 accessor not supported by dart2js`

### ISSUE THREAD

**Issue by josxha** [bramp/pmtiles-dart#2]
pmtiles can't be used on web at the moment because of 
```console
Unsupported operation: Uint64 accessor not supported by dart2js.
packages/pmtiles/src/header.dart 44:39                                       get rootDirectoryOffset
packages/pmtiles/src/archive.dart 294:15                                     fromReadAt
...
```
`getUint64()` is a function provided by `typed_data` and used here for example:
```dart
  int get rootDirectoryOffset => data.getUint64(0x08, Endian.little);
```
https://github.com/bramp/pmtiles-dart/blob/fc8ed3fa2de2070a866423f9d728edd7f5edd3b7/packages/pmtiles/lib/src/header.dart#L44C1-L51C65

Would it be possible to add a workaround when used on web with dart2js?

**Comment by bramp** [comment]
I'm happy to come up with a workaround, but quickly reading https://github.com/dart-lang/sdk/issues/10275 this might quickly become a pain.

I think the simplest option is to add our own getUint64(), that throws an exception when the value is > 2^53 (which I believe is the largest int javascript can handle).   So in the rare case you are trying to read a file 9 petabyte pmtile, it will break on the web.

Later if we really need it, we can move to bigints or similar, but that would be a larger API change.

**Comment by josxha** [comment]
A 9 PB file indeed sounds like a hard core use case. 😄
It would be even possible to add an own kIsWeb constant since it's just a simple environment check ([see here](https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html)) and throw an exeption on web while keeping `getUint64()` on supported platforms.

**Comment by bramp** [comment]
I figured out you can run `dart test --platform node` to run all the tests via dart2js.  Early reports is a lot of things don't work :)

**Comment by bramp** [comment]
ok I spent way longer on this than expected:

1) Cleaned up some simple issues
* Bit operations (e.g 1<33) truncate to 32 bits in JS
* HTTP/File APIs aren't available in JS
* Fixed UInt64 in JS

2) Changed all the tests to run under node and chrome. This involves quite a big refactor to split the tests into two parts.

3) Added new in memory tests, avoiding the need for HTTP or File APIs

4) and more

However, we still aren't there yet, the latest error is `Unsupported operation: _newZLibInflateFilter`

**Comment by bramp** [comment]
Ok, all fixed! I've released version 1.3.0 which passes [all the tests](https://github.com/bramp/pmtiles-dart/actions/runs/7761151963), I even found and fixed a performance issue that was very apparent when running on Chrome.

**Comment by josxha** [comment]
Great work! Thanks for all your effort! 
It's very interesting to see how dart testing can be done for web.

**Comment by bramp** [comment]
Ya, this dart2js and testing dart for the web was a new one for me.

I look forward to seeing a FlutterMaps demo page in action!

**Comment by josxha** [comment]
You can already have a peek at it if you want: https://flutter-map-plugins.web.app/

Howevery there is one problem with pmtiles for `flutter_map`:
- The pub.dev version 6.1.0 of flutter_map has a bug that renders tiles of the wrong zoom level on the screen ([see here](https://github.com/fleaflet/flutter_map/pull/1718#issuecomment-1800190681)).  This seems to be especially noticable on low zoom levels which the example pmtiles file on the example app only concists of. It's fixed in the master branch but will probably take some time until it gets released on pub.dev (cc @JaffaKetchup).

...and one problem with the integration for `vector_map_tiles`:
- The vector renderer doesn't seem to pick up details for higher zoom levels like for example streets. This is most likely either a problem in `vector_tile_renderer` or there is some difference in the pmtiles mvt tiles and those provided by Mapbox that I'm not aware of ([open issue here](https://github.com/josxha/flutter_map_plugins/issues/17))

All in all I really need to get the pmtiles TileProvider examples in a better shape before showcasing. 😄

**Comment by josxha** [comment]
Quick update: 
- I improved the test coverage for `flutter_map_pmtiles` and documentation.
- `vector_map_tiles` is currently not compatible with web, so I disabled its example when running on web. Other platforms work fine now.
